const LOAD_DATA_SUCCESS = 'LOAD_DATA_SUCCESS';
const START_GAME = 'START_GAME';
const TOGGLE_HINTS = 'TOGGLE_HINTS';
const SET_BOARD_SIZE = 'SET_BOARD_SIZE';
const SELECT_CARD = 'SELECT_CARD';

module.exports = {
    LOAD_DATA_SUCCESS,
    START_GAME,
    TOGGLE_HINTS,
    SET_BOARD_SIZE,
    SELECT_CARD,
};
